app = "your-pizzaz-app"   # change me
primary_region = "ams"

[build]
  dockerfile = "pizzaz_server_node/Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # keep streaming endpoints responsive
  auto_start_machines = true
  min_machines_running = 1    # avoid cold starts for SSE/streaming

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

